function countriesNames() {
  const countryNames: Record<string, string> = {
    AF: "Afghanistan",
    AL: "Albania",
    DZ: "Algeria",
    AR: "Argentina",
    AM: "Armenia",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BH: "Bahrain",
    BD: "Bangladesh",
    BY: "Belarus",
    BE: "Belgium",
    BR: "Brazil",
    BG: "Bulgaria",
    CA: "Canada",
    CL: "Chile",
    CN: "China",
    CO: "Colombia",
    HR: "Croatia",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    EG: "Egypt",
    EE: "Estonia",
    FI: "Finland",
    FR: "France",
    GE: "Georgia",
    DE: "Germany",
    GR: "Greece",
    HU: "Hungary",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran",
    IQ: "Iraq",
    IE: "Ireland",
    IL: "Israel",
    IT: "Italy",
    JP: "Japan",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KW: "Kuwait",
    LB: "Lebanon",
    LY: "Libya",
    LT: "Lithuania",
    LU: "Luxembourg",
    MY: "Malaysia",
    MT: "Malta",
    MX: "Mexico",
    MA: "Morocco",
    NL: "Netherlands",
    NZ: "New Zealand",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PS: "Palestine",
    PH: "Philippines",
    PL: "Poland",
    PT: "Portugal",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    SA: "Saudi Arabia",
    RS: "Serbia",
    SG: "Singapore",
    SK: "Slovakia",
    SI: "Slovenia",
    ZA: "South Africa",
    KR: "South Korea",
    ES: "Spain",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syria",
    TW: "Taiwan",
    TH: "Thailand",
    TN: "Tunisia",
    TR: "Turkey",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UZ: "Uzbekistan",
    VN: "Vietnam",
    YE: "Yemen",
  };
  return countryNames;
}
export default countriesNames;
